### ISSUE TITLE
Add Mixcloud support

### ISSUE THREAD

**Issue by codecat** [codecat/reddit-radio#10]
This might need some official API..

**Comment by KurzaCationer** [comment]
Isn't this like impossible, because mixcloud doesn't allow it.
Like you can try to get it via a different way, but I doubt it.

**Comment by DyonR** [comment]
In Chrome, it is possible to obtain the stream URL. 
1. Open the developer mode panel.
2a. Open the device toggle toolbar.
2b. Select any phone.
3. Browse to a Mixcloud stream page (example: https://m.mixcloud.com/Q-dance/q-dance-presents-the-magic-show-l-week-41/)
4. Start the stream.
5. In the Network section, a URL from streamX.mixcloud.com/secure/........ should appear, this is the actual stream URL.

Problem: Mixcloud throttles the download speed to <20KB/s, making it practically unusable for re-streaming. (Great for offline saving, bad for streaming).
Problem 2: It is uncertain if it is possible to actually receive this URL using a simple script

Using an official API won't solve this problem either:
"The audio streams are not available through the Mixcloud API."
See https://www.mixcloud.com/developers/#audio-streams for more information.

**Comment by codecat** [comment]
I thought the 20KB/s thing was because it's the approximate speed of the actual audio streaming?

**Comment by DyonR** [comment]
That sounds logical, as 20KB/s == 160KBit/s, since it is a stream, this would be perfect.
