### ISSUE TITLE
Automatically connect when .play has been used.

### ISSUE THREAD

**Issue by DyonR** [codecat/reddit-radio#12]
When .play <url> has been used, while the bot has not been connected, it should automatically connect.
This could reduce the amount of effort used to play a song.
For example this could happen:
User: .play <url>
Bot: I'm not in a voice channel. 🤔
User: .connect
Bot: Hello! 👋
User: .play <url>
Bot: Okay, I added it to the jukebox! 🎵

With an automatically connect when .play has been used, this could be reduced to this:
User: .play <url>
Bot: Hello! 👋
Bot: Okay, I added it to the jukebox! 🎵

**Comment by codecat** [comment]
Fixed with #15
