### ISSUE TITLE
Command: .hbnp

### ISSUE THREAD

**Issue by codecat** [codecat/reddit-radio#14]
Not entirely sure if they have a real API..

URL: `https://www.hardbase.fm/`

**Comment by DyonR** [comment]
They have a real API.
https://api.tb-group.fm/v1/radio
Edit:
Alternative, better:
https://api.tb-group.fm/v1/tracklist/7
a = Artist
t = Track
p = Unix time with 3 times 0 on the end
u = HardBaseFM DJ
i = Image URL LQ
r = TrackID? Can be used for HQ image, exmaple URL: https://api.tb-group.fm/images/release/14468

**Comment by codecat** [comment]
Thanks!
