### ISSUE TITLE
Add the ability to automatically search SoundCloud/YouTube

### ISSUE THREAD

**Issue by DyonR** [codecat/reddit-radio#16]
Instead of providing a full url to a SoundCloud/YouTube page, it would nice if the bot could automatically search SoundCloud and YouTube.
Example;
Instead of using this command:
.play https://soundcloud.com/hardstyle/sephyx-monster

You would be able to use the following:
.play sephyx monster
The bot would search SoundCloud and takes the best match, if nothing has been found, it should search on YouTube.

**Comment by codecat** [comment]
YouTube was added via #17

**Comment by codecat** [comment]
Soundcloud was added, too
