### ISSUE TITLE
Clean up logging for jukebox commands (on track end in particular)

### ISSUE THREAD

**Issue by codecat** [codecat/reddit-radio#3]
Stuff like starting, pausing, resuming, errors, etc.

**Comment by vzqzac** [comment]
Hey I can take this, any issue on labeling as already assigned?

**Comment by codecat** [comment]
I think your comment is fine enough to show that someone is working on this. Thanks for the interest!

**Comment by vzqzac** [comment]
@codecat could you be more specific on where should the logs be added? I only found one spot on `start()` function were there is a missing log for the command line, but I don't know which others should I add

**Comment by codecat** [comment]
It should probably print logs when a song starts, when it ends with an error, and when the bot joins or leaves the voice channel.

**Comment by codecat** [comment]
Ended up doing some of this logging myself as we needed it pretty urgently. Still can have some cleaning up though.
