### ISSUE TITLE
Update the Q-dance Radio Bot profile picture

### ISSUE THREAD

**Issue by DyonR** [codecat/reddit-radio#31]
Q-dance has a new logo for quite some time, but the bot it still using the old logo as profile picture.
I have prepared a few new image for the profile picture that can be found at:
https://dyonr.nl/q-dance_logos/

I think the https://dyonr.nl/q-dance_logos/q-dance_transparent_1024x1024.png should be good.

**Comment by codecat** [comment]
I used the dark one, thx! 👍 

![image](https://user-images.githubusercontent.com/136534/79371749-281a9580-7f55-11ea-8b69-41c09333aa6b.png)
